# Generated by Django 4.0.4 on 2022-05-13 07:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(max_length=500)),
                ('height', models.PositiveBigIntegerField(default=170)),
                ('weight', models.PositiveBigIntegerField(default=90)),
                ('wins', models.PositiveBigIntegerField(default=0)),
                ('losses', models.PositiveBigIntegerField(default=0)),
                ('no_contest', models.PositiveBigIntegerField(default=0)),
                ('rank', models.CharField(blank=True, choices=[('JONOKUCHI', 'JONOKUCHI'), ('JONIDAN', 'JONIDAN'), ('SANDANME', 'SANDANME'), ('MAKUSHITA', 'MAKUSHITA'), ('JURYO', 'JURYO'), ('MAEGASHIRA', 'MAEGASHIRA'), ('MAEGASHIRA', 'MAEGASHIRA'), ('KOMUSUBI', 'KOMUSUBI'), ('SEKIWAKE', 'SEKIWAKE'), ('OZEKI', 'OZEKI'), ('YOKOZUNA', 'YOKOZUNA')], max_length=255, null=True)),
                ('championships', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
