# Generated by Django 4.0.4 on 2022-05-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='championships',
            field=models.TextField(),
        ),
    ]
