# Generated by Django 4.0.4 on 2022-05-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_pro_championships'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pros/'),
        ),
    ]
